print("""

           X           X
          XX           XX
         XXX           XXX
        XXX X          X XX
        XXX X          X XXX
        XXX X          X XXX
        XXX X          X XXX
        XXX X          X XXX
         XX X          X XX
         XXXX          XXXX
          XXX          XXX
          XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXX
         XXX 0 XXXXXX 0 XXX
         XXXXXXXXXXXXXXXXXX
          XXXXXX\  /XXXXXX
           XXXXXXXXXXXXXX
            XXXXXXXXXXXX
           XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX XXXXXXXXXX XXXXX xXX
XXXXXXXX xXXXXXXXXX XXXXX XXX
XXXXXXXX XXXXXXXXXX XxXXX XXX
XXXXXXXXXXX XXXXXXX XxXXX XXX
XXXXXXXXXXXX XXXXXX XxXXX XXX
XXXXXXXXXXXXXX XXXX XXXXXX XXxx      
XXXXXXXXXXXXXx XXXX XXXXXX XXXX______\\/__________\//_______//___________


""")
